Django/locallibrary/catalog/urls.py
from django.urls import path
from . import views

"""
When this urlpatterns is checked,
the url has already been matched for catalog/.
Hence all paths in this are catalog/$
"""

urlpatterns = [
    path('', views.index, name='index'),
    path('books', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailsView.as_view(), name='book-details'), 
]

Django/locallibrary/locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


"""
1.  Instead of adding all mappings here,
    it's considered good practice to defer it
    to the app
2.  Configuring the root path to display
    the catalog page.
"""

urlpatterns = [
    path('admin/', admin.site.urls),

    path('catalog/', include('catalog.urls')),

    path('', RedirectView.as_view(url='catalog/')),

    path('account/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Django/locallibrary/catalog/models.py
from django.db import models
from django.urls import reverse

import uuid

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=15, help_text='Enter a book genre: ')

    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=100)

    """
    You must use the name of the Object, if it hasn't
    been defined in the file before referencing.
    """
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)

    # The max_length is imposed by the view, not the Database.
    summary = models.TextField(max_length=1000, help_text='Enter a summary about the book')

    # Providing the first parameter to specify how isbn will be represented in View, default
    # would be Isbn
    isbn = models.CharField('ISBN', max_length=13, help_text='13 character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number </a>')

    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')

    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True,default='eng', help_text='Select the language for this book')

    """
    Here book-details is the name provided in the URL mapper to the
    URL that displays details of books.
    If the URL accepts arguments, you can pass those in the args
    parameter.
    """
    def get_absolute_url(self):
        return reverse('book-details', args=[str(self.id)])

    def __str__(self):
        return self.title
    
    def display_genre(self):
        # The [:3] restricts display to only 3 genres.
        return ', '.join(genre.name for genre in self.genre.all()[:3])



class BookInstance(models.Model):

    """
    By default the primary key is set to be an 
    AutoField, however you can explicitly set
    using UUIDField. This would lead to an explicit
    ID field which will appear (already populated)
    on the Admin Page.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book, across the whole library')
    book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    
    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_back']
    
    def __str__(self):
        return f'{self.id} ({self.book.title})'
    

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)

    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['first_name', 'last_name']

    def get_absolute_url(self):
        return reverse('author-details', args=[str(self.id)])

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

class Language(models.Model):
    LANGUAGE_LIST = (
        ('eng', 'English' ),
        ('fre', 'French'),
        ('jap', 'Japanese')
    )

    language = models.CharField(max_length=30,
                choices=LANGUAGE_LIST,
                blank=True,
                default='eng',
                help_text='Book language')

    def __str__(self):
        return (self.language)

Django/locallibrary/catalog/views.py
from django.shortcuts import render
from django.views import generic
from .models import Book, BookInstance, Author, Genre

# Create your views here.

def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    num_instances_available = BookInstance.objects.filter(status__exact='a').count()

    num_authors = Author.objects.all().count()

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1 

    context = {
        'num_books' : num_books,
        'num_instances' : num_instances,
        'num_instances_available' : num_instances_available,
        'num_authors' : num_authors,
        'num_visits' : num_visits
    }

    return render(request, 'index.html', context=context)

# This searches for template in templates/catalog/book_list.html
class BookListView(generic.ListView):
    model = Book
    paginate_by = 2

# This is passed in for a single object.
class BookDetailsView(generic.DetailView):
    model = Book

Django/locallibrary/catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {% block title %}
            <title>Local Library</title>
        {% endblock %}
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
            crossorigin="anonymous"
        />
        {% load static %}
        <link  rel="stylesheet" type="text/css" href={% static 'css/main.css'%}>
    </head>
    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-2">
                    {% block sidebar %}
                        <ul class="sidebar-nav">
                            <li><a href="{% url 'index' %}">Home</a></li>
                            <li><a href="{% url 'books' %}">All books</a></li>
                            <li><a href="">All authors</a></li>
                        </ul>
                    {% endblock %}
                </div>
                <div class="col-sm-10">
                    {% block content %} {% endblock %}
                    {% block pagination %}
                        {% if is_paginated %}
                            <div class="pagination">
                                <span class="page-links">
                                    {% if page_obj.has_previous %}
                                        <a href="{{requestpath}}?page={{page_obj.previous_page_number}}">previous</a>
                                    {% endif %}
                                    <span class="page-current">
                                        Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}
                                    </span>
                                    {% if page_obj.has_next %}
                                        <a href="{{requestpath}}?page={{page_obj.next_page_number}}">Next</a>
                                    {% endif %}
                                </span>
                            </div>
                        {% endif %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

Django/locallibrary/catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

<!-- The book object is available as book -->
{% block content %}
    <h1> Title: {{book.title}}</h1>
    <p><strong>Author:</strong> <a href="#">{{ book.author }}</a></p>
    <p><strong>Summary:</strong> {{ book.summary }}</p>
    <p><strong>ISBN:</strong> {{ book.isbn }}</p> 
    <p><strong>Language:</strong> {{ book.language }}</p>
    <!-- This is an example of a filter.
    See: https://docs.djangoproject.com/en/3.0/ref/templates/language/ -->
    <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p> 

    <div>
        <h4>Copies:</h4>
        {% for copy in book.bookinstance_set.all %}
            <hr>
            <p class="{% if copy.status == 'a' %} text-success {% elif copy.status == 'm' %} text-danger {% else %} text-warning {% endif %} ">
                {{ copy.get_status_display }}
            </p>
            {% if copy.status != 'a' %}
                <p><strong> Due to be returned by: </strong>{{copy.due_back}}</p>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

Django/locallibrary/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>
        Book List
    </h1>
    {% if book_list %}
    <ul>
        {% for book in book_list %}
            <!-- call as function here or member -->
           <li>
                <a href="{{book.get_absolute_url}}">{{book.title}}</a> {{book.author}}
           </li> 
        {% endfor %}
    </ul>
    {% else %}
        <p>There are no books to display</p>
    {% endif %}

{% endblock %}

Django/locallibrary/catalog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Local Library Home</h1>
  <p>Welcome to LocalLibrary</p>
  <h2>Dynamic content</h2>
  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
  </ul>
  <p>You've visited this page {{num_visits}} {% if num_visits == 1 %}time{% else %}times{% endif %}</p>
{% endblock %}